name: wheretosleepinnju
description: wheretosleepinnju

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 3.3.5+55

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  shared_preferences: 
    path: ./external/flutter_packages/packages/shared_preferences/shared_preferences
  # Android iOS Linux macOS web Windows HarmonyOS

  webview_flutter: 
    path: ./external/flutter_packages/packages/webview_flutter/webview_flutter
  # Android iOS HarmonyOS

  path_provider:
    path: ./external/flutter_packages/packages/path_provider/path_provider
  # Android iOS Linux macOS     Windows HarmonyOS

  url_launcher: 
    path: ./external/flutter_packages/packages/url_launcher/url_launcher
  # Android iOS Linux macOS web Windows

  image_picker:
    path: ./external/flutter_packages/packages/image_picker/image_picker
  # Android iOS             web harmonyos

  sqflite: ^2.0.0+4
  # Android iOS       macOS
  
  flutter_swiper_null_safety_flutter3: ^2.0.0
  # Android iOS Linux macOS web Windows
  scoped_model: ^2.0.0-nullsafety.0
  # Android iOS Linux macOS web Windows
  azlistview: ^2.0.0-nullsafety.0
  # Android iOS Linux macOS web Windows
  flutter_native_splash: ^2.0.5
  # Android iOS             web
  # flutter_search_bar: ^3.0.0-dev.1
  # Android iOS Linux macOS web Windows

  umeng_common_sdk: ^1.2.7
#    path: ./external/umeng_common_sdk
  # Android iOS
#  qr_code_scanner: ^1.0.1
  # Android iOS
  flutter_linkify: ^6.0.0
  # Android iOS Linux macOS web Windows
  
  # auto_size_text: ^3.0.0
  # Android iOS Linux macOS web Windows
  
  in_app_review: ^2.0.3
  # Android iOS       macOS
  # 但是只用在 iOS
  package_info_plus: ^9.0.0
  # Android iOS       macOS
  flutter_html: ^3.0.0-alpha.5
  # Android iOS
#  share_extend: ^2.0.0
  # Android iOS
  fluttertoast: ^8.0.1
  # Android iOS             web
  qr_flutter: ^4.0.0
  # Android iOS Linux macOS web Windows
  html: ^0.15.0
  # Android iOS Linux macOS web Windows
  dio: ^5.9.0
  # Android iOS Linux macOS web Windows
  device_calendar: ^4.2.0
#  flutter_timezone: ^3.0.0

dependency_overrides:
  scrollable_positioned_list: 0.3.2
  url_launcher:
    path: ./external/flutter_packages/packages/url_launcher/url_launcher
    
  shared_preferences:
    path: ./external/flutter_packages/packages/shared_preferences/shared_preferences
    
  webview_flutter:
    path: ./external/flutter_packages/packages/webview_flutter/webview_flutter
    
  path_provider:
    path: ./external/flutter_packages/packages/path_provider/path_provider
    
  image_picker:
    path: ./external/flutter_packages/packages/image_picker/image_picker

  sqflite:
    path: ./external/flutter_sqflite/sqflite

  sqflite_common:
    path: ./external/flutter_sqflite/sqflite_common

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - res/icon.png

flutter_intl:
  enabled: true

analyzer:
  strong-mode: true
  language:
    enableSuperMixins: true

flutter_native_splash:
  color: "#ffffff"
#  image: res/icon.png
  color_dark: "#000000"
#  image_dark: res/icon.png
